docker-pull: Group error handling
If the cmd exits 1, echo will be called (and exit 0) then will cause the
whole thing to exit 1. Fix this by grouping the error handling to run
together instead of sequentially.

```
% true || true && false
% echo $?
1
```
and
```
% true || {true && false}
% echo $?
0
```

diff --git a/bin/docker-pull b/bin/docker-pull
--- a/bin/docker-pull
+++ b/bin/docker-pull
@@ -21,17 +21,17 @@ else
   case $EXTERNAL_REGISTRY_BASE_DOMAIN in
     *amazonaws.com*)
       "${DIR}/registries/docker-pull.ecr.sh" ||
-        echo "Could not authenticate." && exit 1
+        { echo "Could not authenticate." && exit 1; }
       ;;
 
     *gcr.io*)
       "${DIR}/registries/docker-pull.gcr.sh" ||
-        echo "Could not authenticate." && exit 1
+        { echo "Could not authenticate." && exit 1; }
       ;;
 
     *quay.io*)
       "${DIR}/registries/docker-pull.quay.sh" ||
-        echo "Could not authenticate." && exit 1
+        { echo "Could not authenticate." && exit 1; }
       ;;
 
   esac
